-url: db/journals/bioinformatics/bioinformatics38.html#WaeleCMW22

-url: db/journals/ml/ml111.html#IliadisBW22

-url: db/journals/tcbb/tcbb19.html#ClauwaertW22

-url: db/journals/corr/corr2203.html#abs-2203-06102

-url: db/journals/corr/corr2203.html#abs-2203-06676

-url: db/journals/corr/corr2205.html#abs-2205-10082

-url: db/journals/bib/bib22.html#ClauwaertMW21

-url: db/journals/datamine/datamine35.html#MortierWDHW21

-url: db/journals/ml/ml110.html#HullermeierW21

-url: db/journals/corr/corr2104.html#abs-2104-09967

-url: db/journals/corr/corr2107.html#abs-2107-00363

-url: db/journals/bib/bib21.html#StockPAWB20

-url: db/journals/cmpb/cmpb173.html#DeschepperEVW19

-url: db/journals/datamine/datamine33.html#WaegemanDH19

-url: db/conf/bnaic/bnaic2019.html#MortierWDHW19

-url: db/conf/bnaic/bnaic2019.html#Papagiannopoulou19

-url: db/conf/pkdd/pkdd2019-3.html#Papagiannopoulou19

-url: db/journals/corr/corr1906.html#abs-1906-08129

-url: db/journals/corr/corr1910.html#abs-1910-09457

-url: db/journals/neco/neco30.html#StockPABW18

-url: db/conf/pkdd/pkdd2018-1.html#DecubberMDW18

-url: db/journals/corr/corr1803.html#abs-1803-01575

-url: db/journals/corr/corr1809.html#abs-1809-02352

-url: db/conf/multitemp/multitemp2017.html#MartensMDWV17

-url: db/conf/multitemp/multitemp2017.html#MirallesDVDPDW17

-url: db/conf/pkdd/pkdd2017-3.html#Papagiannopoulou17

-url: db/journals/datamine/datamine30.html#StockDBW16

-url: db/conf/pkdd/pkdd2016-2.html#DembczynskiKWBH16

-url: db/journals/corr/corr1606.html#StockPABW16

-url: db/journals/corr/corr1606.html#StockDBW16

-url: db/journals/cea/cea111.html#ColmanWBF15

-url: db/journals/corr/corr1506.html#PahikkalaVAW15

-url: db/journals/ecoi/ecoi22.html#PetersWdDCLVB14

-url: db/journals/jmlr/jmlr15.html#WaegemanDJCH14

-url: db/journals/tcbb/tcbb11.html#StockFHGKPABW14

-url: db/conf/pkdd/pkdd2014-2.html#PahikkalaSAABW14

-url: db/journals/corr/corr1405.html#StockFHGKPABW14

-url: db/journals/corr/corr1405.html#PahikkalaSAABW14

-url: db/journals/envsoft/envsoft47.html#FukudaBWVM13

-url: db/journals/ml/ml93.html#PahikkalaASBW13

-url: db/conf/icml/icml2013.html#DembczynskiJKWH13

-url: db/journals/corr/corr1310.html#WaegemanDCH13

-url: db/journals/csda/csda56.html#VerwaerenWB12

-url: db/journals/ml/ml88.html#DembczynskiWCH12

-url: db/journals/tfs/tfs20.html#WaegemanPASSB12

-url: db/conf/ecai/ecai2012.html#DembczynskiWH12

-url: db/conf/nips/nips2012.html#ChengHWW12

-url: db/conf/rsctc/rsctc2012.html#ChengDHJW12

-url: db/journals/corr/corr1209.html#abs-1209-4825

-url: db/journals/ai/ai175.html#WaegemanB11

-url: db/journals/csda/csda55.html#AirolaPWBS11

-url: db/journals/fss/fss184.html#WaegemanVSB11

-url: db/conf/eurofuse/eurofuse2011.html#WaegemanPASB11

-url: db/conf/eurofuse/eurofuse2011.html#FukudaWMB11

-url: db/conf/gefs/gefs2011.html#FukudaNBWMMO11

-url: db/conf/isda/isda2011.html#WaegemanB11

-url: db/conf/nips/nips2011.html#DembczynskiWCH11

-url: db/journals/corr/corr1111.html#abs-1111-6473

-url: db/journals/bmcbi/bmcbi11.html#SlabbinckWDVB10

-url: db/journals/eor/eor206.html#PahikkalaWTSB10

-url: db/journals/isci/isci180.html#WaegemanB10

-url: db/conf/esann/esann2010.html#DevlaminckWBWOBS10

-url: db/conf/nabic/nabic2010.html#FukudaOBWMNM10

-url: db/conf/pkdd/pkdd2010-1.html#DembczynskiWCH10

-url: db/conf/pkdd/pkdd2010-2.html#PahikkalaWASB10

-url: db/journals/jmlr/jmlrp8.html#AirolaPWBS10

-url: db/books/collections/FH2010.html#WaegemanB10

-url: db/journals/4or/4or7.html#WaegemanBB09

-url: db/journals/4or/4or7.html#Waegeman09

-url: db/journals/csda/csda52.html#WaegemanBB08

-url: db/journals/eaai/eaai21.html#WaegemanCWBBLD08

-url: db/journals/nn/nn21.html#WaegemanBB08

-url: db/journals/prl/prl29.html#WaegemanBB08